services:
  sonarr:
    user: 0:666
    image: lscr.io/linuxserver/sonarr:latest 
    container_name: sonarr
    networks:
      - proxy
    hostname: sonarr
    volumes:
      - ./config:/config
      - /media:/media
      - /downloads:/downloads
      - /downloads:/download
    environment:
      - APP_GROUP=Requests
      - APP_LOGO=https://res.cloudinary.com/razordarkamg/image/upload/v1621212884/SonarrV3_pufacd.png
      - VIRTUAL_HOST=sonarr.admin.pknw1.co.uk
      - VIRTUAL_PORT=8989

networks:
  proxy:
    external: true

